services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod  
    container_name: underwriting_app
    restart: always
      - ENV=dev
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/underwriting_dev
      - REDIS_URL=redis://redis:6379/0
      - MAIL_SERVER=smtp
      - MAIL_PORT=587
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    depends_on:
      - db
      - redis
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: underwriting_nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ../config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../config/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      app:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: underwriting_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: underwriting
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: underwriting_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Optional: Persist Redis data

volumes:
  pg_data:
  redis_data:  # Optional: Redis persistence
