version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod  
    container_name: underwriting_app
    restart: always
    environment:
      - ENV=prod
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - MAIL_SERVER=smtp
      - MAIL_PORT=587
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: ["poetry", "run", "gunicorn", "-w", "2", "--timeout", "120", "-b", "0.0.0.0:8000", "src.app:app"]

  nginx:
    image: nginx:latest
    container_name: underwriting_nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ../config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../config/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      app:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: underwriting_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: underwriting
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:latest
    container_name: underwriting_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3
      timeout: 3s

volumes:
  pg_data:
  redis_data:
