FROM python:3.10.13

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    POETRY_VERSION=2.1.1 \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_NO_INTERACTION=1

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

# Install Poetry
RUN pip install --no-cache-dir "poetry==$POETRY_VERSION"

# Copy dependency files first
COPY pyproject.toml poetry.lock README.md ./

# Install dependencies
RUN poetry install --no-root --no-ansi

# Copy the rest of the application
COPY . .

# Run tests
CMD ["sh", "-c", "poetry run pytest --cov=src --cov-report=xml --html=reports/test_report.html --self-contained-html"]
